DROP TABLE IF EXISTS idiom;
DROP TABLE IF EXISTS form_idiom;

CREATE TABLE idiom (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR
);

CREATE TABLE form_idiom (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR,
idiom_id INTEGER,
FOREIGN KEY (idiom_id) REFERENCES idiom(id)
);
