DROP TABLE IF EXISTS idiom;
DROP TABLE IF EXISTS form_idiom;

CREATE TABLE idiom (
name VARCHAR PRIMARY KEY,
);

CREATE TABLE form_idiom (
name VARCHAR PRIMARY KEY,
idiom_id INTEGER,
FOREIGN KEY (idiom_id) REFERENCES idiom(name)
);
